// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goqpmokzsvausgwaignw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcXBtb2t6c3ZhdXNnd2FpZ253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDAyMzAsImV4cCI6MjA2MzMxNjIzMH0.MLE17Jduz4VzYHf5WbX6mRxuP4mrq-BSGA1k2UPCh9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);